# Generated by Django 5.2.8 on 2025-11-27 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True)),
                ('definicao', models.TextField()),
                ('categoria', models.CharField(choices=[('TI', 'Tecnologia da Informação'), ('GE', 'Gestão'), ('FIN', 'Finanças'), ('OUT', 'Outros')], default='OUT', max_length=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['termo'],
            },
        ),
    ]
