# Generated by Django 5.2.8 on 2025-12-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='categoria',
            field=models.CharField(choices=[('PROG', 'Programação e Desenvolvimento'), ('DBA', 'Banco de Dados (DBA)'), ('CLOUD', 'Cloud Computing'), ('REDES', 'Redes e Segurança'), ('UXUI', 'UX/UI Design'), ('GERAL', 'Geral de TI')], default='GERAL', max_length=10),
        ),
    ]
