# Generated by Django 5.2.8 on 2025-12-07 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_termo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termo',
            options={'ordering': ['termo'], 'verbose_name_plural': 'Termos'},
        ),
        migrations.AlterField(
            model_name='termo',
            name='categoria',
            field=models.CharField(choices=[('PROG', 'Programação e Desenvolvimento'), ('DBA', 'Banco de Dados (DBA)'), ('CLOUD', 'Cloud Computing'), ('REDES', 'Redes e Segurança'), ('UXUI', 'UX/UI Design'), ('GERAL', 'Geral de TI')], default='GERAL', max_length=10, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='termo',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='termos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Autor/Colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termo',
            name='definicao',
            field=models.TextField(verbose_name='Definição Completa'),
        ),
        migrations.AlterField(
            model_name='termo',
            name='termo',
            field=models.CharField(error_messages={'unique': 'Já existe um termo cadastrado com este título. Por favor, escolha um título diferente.'}, max_length=100, unique=True, verbose_name='Título do Termo'),
        ),
    ]
